"""Builds the three-digit ZIP table Safe Harbor's postal-code rule reads.

45 CFR 164.514(b)(2)(i)(B) lets a de-identified record keep the first three digits of a ZIP code only where
"the geographic unit formed by combining all ZIP codes with the same three initial digits contains more than
20,000 people", according to "the current publicly available data from the Bureau of the Census". Every
other prefix becomes 000.

HHS's guidance (26 November 2012, section 3.1) prints a list of 17 prefixes from the 2000 census, and in the
same paragraph says not to rely on it "if more current data has been published". It has been, twice. Against
the 2020 count that list keeps six prefixes it should zero (202, 204, 205, 369, 753, 772) and zeroes five it
could keep. So this script derives the table from the 2020 Decennial Census instead, the way HHS derived its
own: total population (P1_001N) of every ZIP Code Tabulation Area, summed by its first three digits.

The file it writes lists every prefix that has at least one ZCTA, with its population. The engine applies the
threshold, and a prefix that is not in the file at all -- military APO/FPO ranges, unassigned ranges, ZIPs
that are only post-office boxes -- has no people the census can count, so it becomes 000 too. The table is an
allow-list by construction: a prefix nobody measured is not kept.

Run from the repository root:  python tools/census/zip3.py
It needs no key. Re-running it on the same day's data reproduces the file byte for byte; the sha256 of the
response is recorded so a reader can tell whether the Census Bureau has since changed what it serves.
"""

import collections
import datetime
import hashlib
import io
import json
import urllib.request

URL = 'https://data.census.gov/api/access/data/table?g=010XX00US$8600000&id=DECENNIALDHC2020.P1'
OUT = 'src/Silueta.Core/Transform/Tables/zip3.census-2020.json'
THRESHOLD = 20000


def main():
    # data.census.gov refuses Python's default user agent; it serves anything that names itself.
    request = urllib.request.Request(URL, headers={'User-Agent': 'silueta-zip3/1 (+https://github.com/peopleworks/Silueta)'})
    raw = urllib.request.urlopen(request, timeout=120).read()
    response = json.loads(raw)['response']
    header, rows = response['data'][0], response['data'][1:]
    assert header == ['GEO_ID', 'P1_001NA', 'P1_001N', 'NAME'], header

    populations = collections.Counter()
    total = 0
    for geo_id, annotation, population, name in rows:
        zcta = geo_id[-5:]
        assert geo_id.startswith('860Z200US') and name == 'ZCTA5 ' + zcta and zcta.isdigit(), (geo_id, name)
        assert annotation is None, (geo_id, annotation)
        populations[zcta[:3]] += int(population)
        total += int(population)

    table = {
        '_about': [
            'Three-digit ZIP prefixes and the people living in them, from the 2020 Census. Safe Harbor keeps a',
            'prefix only where this number is above 20,000; below it, and for any prefix not listed here, the',
            'prefix becomes 000. Generated by tools/census/zip3.py -- edit that, not this.',
        ],
        'table': 'zip3/census-2020',
        'rule': '45 CFR 164.514(b)(2)(i)(B)',
        'threshold': THRESHOLD,
        'source': {
            'dataset': '2020 Census Demographic and Housing Characteristics File (DHC), table P1, P1_001N total population',
            'geography': 'every ZIP Code Tabulation Area (ZCTA5), summed by its first three digits',
            'url': URL,
            'api': response['dataAPIURI'],
            'retrieved': datetime.date.today().isoformat(),
            'sha256': hashlib.sha256(raw).hexdigest(),
            'zctas': len(rows),
            'population': total,
        },
        'populations': dict(sorted(populations.items())),
    }

    text = json.dumps(table, indent=2, ensure_ascii=False)
    # One line per prefix would be nine hundred lines; eight to a line keeps the file readable end to end.
    entries = [f'"{prefix}": {count}' for prefix, count in sorted(populations.items())]
    lines = ['    ' + ', '.join(entries[i:i + 8]) for i in range(0, len(entries), 8)]
    head = text[:text.index('"populations": {') + len('"populations": {')]
    text = head + '\n' + ',\n'.join(lines) + '\n  }\n}\n'
    json.loads(text)  # still JSON after the reflow

    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as out:
        out.write(text)

    kept = sum(1 for count in populations.values() if count > THRESHOLD)
    print(f'{len(rows)} ZCTAs, {total} people, {len(populations)} prefixes: {kept} kept, '
          f'{len(populations) - kept} zeroed, {1000 - len(populations)} with no ZCTA (zeroed).')


if __name__ == '__main__':
    main()
